#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
22_haplotype_first_interpretation.py
====================================

Build a haplotype-first interpretation layer on top of the existing
frequency/association outputs without changing the underlying tests.
"""

from __future__ import annotations

import math
import re
from pathlib import Path
from typing import Iterable

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from pipeline_utils import get_paths

FDR_THRESHOLD = 0.10
PRIMARY_COMPARISONS = ("Breast", "All", "Endometrium")
HAP_EFFECT_COLORS = {
    "Tumour-enriched": "#b2182b",
    "Healthy-enriched": "#2166ac",
    "Balanced": "#6c757d",
}
COMPARISON_MARKERS = {
    "Breast": "s",
    "All": "o",
    "Endometrium": "^",
}


def harmonised_defaults() -> dict[str, Path]:
    paths = get_paths()
    hap_stats = paths["haplotype_results"]
    return {
        "hap_stats": hap_stats,
        "hap_stats_female": hap_stats.with_name("GSDMB_Haplotype_Results_FemaleOnly_StudySamples.xlsx"),
        "snp_enrichment": paths["snp_enrichment_dir"] / "GSDMB_SNP_Enrichment_Results.xlsx",
        "hap_compare": paths["thousand_genomes_results"] / "19_1000G_Haplotype_Comparison.xlsx",
        "phased": paths["haplotype_phased"],
        "sample_meta": paths["haplotype_phased_dir"] / "sample_metadata.tsv",
        "out_dir": paths["results_dir"] / "22_haplotype_first_interpretation",
    }


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def read_excel(path: Path, sheet_name: str) -> pd.DataFrame:
    return pd.read_excel(path, sheet_name=sheet_name)


def inspect_female_subset_workbook(path: Path) -> dict[str, object]:
    info: dict[str, object] = {
        "available": False,
        "verified": False,
        "sample_filter_mode": "",
        "sample_filter_file": "",
        "analysis_label": "",
        "note": "Female-only study subset workbook not found; study-only female frequency checks will be left missing.",
    }
    if not path.exists():
        return info

    info["available"] = True
    try:
        xl = pd.ExcelFile(path)
    except Exception as exc:
        info["note"] = f"Female-only study subset workbook could not be opened: {exc}"
        return info

    if "Analysis_Metadata" not in xl.sheet_names:
        info["note"] = "Female-only study subset workbook is present but has no Analysis_Metadata sheet, so the sample filter cannot be verified."
        return info

    meta = pd.read_excel(path, sheet_name="Analysis_Metadata")
    if {"Setting", "Value"}.issubset(meta.columns):
        meta_map = dict(zip(meta["Setting"].astype(str), meta["Value"]))
    else:
        meta_map = {}
    info["sample_filter_mode"] = str(meta_map.get("Sample_Filter_Mode", "") or "")
    info["sample_filter_file"] = str(meta_map.get("Sample_Filter_File", "") or "")
    info["analysis_label"] = str(meta_map.get("Analysis_Label", "") or "")
    info["verified"] = info["sample_filter_mode"] == "ExplicitSampleList"
    if info["verified"]:
        info["note"] = "Female-only study frequency checks use the explicit study-sample subset workbook generated by stage 15R."
    else:
        info["note"] = "Female-only study subset workbook is present but not marked as an explicit sample-list rerun; female study frequencies will be treated as unverified."
    return info

def load_significant_haplotypes(hap_stats_path: Path) -> pd.DataFrame:
    xl = pd.ExcelFile(hap_stats_path)
    frames = []
    pattern = re.compile(r"^LD_Block_r2_080_Block\d+_Assoc$")
    for sheet in xl.sheet_names:
        if sheet != "Full_Associations" and not pattern.match(sheet):
            continue
        df = read_excel(hap_stats_path, sheet)
        if "Significant_FDR" not in df.columns:
            continue
        df = df[df["Significant_FDR"].eq(True) & df["Comparison"].isin(PRIMARY_COMPARISONS)].copy()
        if df.empty:
            continue
        df["Assoc_Sheet"] = sheet
        frames.append(df)
    if not frames:
        return pd.DataFrame()

    sig = pd.concat(frames, ignore_index=True)
    sig = sig[sig["Region"].eq("Full_Region") | sig["Region"].str.fullmatch(r"LD_Block_r2_080_Block\d+", na=False)].copy()
    sig["Haplotype_Effect"] = np.where(
        sig["OR"] > 1,
        "Tumour-enriched",
        np.where(sig["OR"] < 1, "Healthy-enriched", "Balanced"),
    )
    sig["Primary_Comparison_Rank"] = sig["Comparison"].map({"Breast": 0, "All": 1, "Endometrium": 2})
    sig = sig.sort_values(["FDR", "P_Fisher", "Primary_Comparison_Rank", "Region", "Haplotype_ID"], kind="stable")
    return sig.reset_index(drop=True)


def load_significant_snps(snp_results_path: Path) -> pd.DataFrame:
    comparison_map = {"Global": "All", "Breast": "Breast", "Endometrium": "Endometrium"}
    frames = []
    for sheet, comparison in comparison_map.items():
        df = read_excel(snp_results_path, sheet)
        df = df[df["FDR_Significant"].eq(True)].copy()
        if df.empty:
            continue
        df["Comparison"] = comparison
        frames.append(df)
    sig = pd.concat(frames, ignore_index=True)
    sig["SNP_Effect"] = np.where(
        sig["Odds_Ratio"] > 1,
        "Tumour-enriched",
        np.where(sig["Odds_Ratio"] < 1, "Healthy-enriched", "Balanced"),
    )
    return sig.sort_values(["Comparison", "FDR_P_Value", "P_Value", "SNP_ID"], kind="stable").reset_index(drop=True)


def load_region_lookup(
    hap_stats_path: Path,
    compare_path: Path,
) -> tuple[pd.DataFrame, dict[str, list[str]], dict[str, list[int]], dict[str, tuple[int, int]]]:
    snps_used = read_excel(hap_stats_path, "SNPs_Used").rename(columns={"POS_int": "POS", "rsID_clean": "rsID"})
    full_region_rsids = snps_used["rsID"].dropna().astype(str).tolist()
    full_region_pos = snps_used["POS"].dropna().astype(int).tolist()

    ld_blocks = read_excel(compare_path, "Study_LD_Blocks")
    ld_blocks["POS"] = ld_blocks["POS"].astype(int)
    ld_blocks["Region"] = ld_blocks["Region"].astype(str)

    region_to_rsids = {"Full_Region": full_region_rsids}
    region_to_pos = {"Full_Region": full_region_pos}
    region_to_span = {"Full_Region": (min(full_region_pos), max(full_region_pos))}
    for region, sub in ld_blocks.groupby("Region", sort=False):
        ordered = sub.sort_values("POS")
        rsids = ordered["rsID"].astype(str).tolist()
        pos = ordered["POS"].astype(int).tolist()
        region_to_rsids[region] = rsids
        region_to_pos[region] = pos
        region_to_span[region] = (min(pos), max(pos))
    return snps_used, region_to_rsids, region_to_pos, region_to_span


def load_freq_sheet_definitions(
    hap_stats_path: Path,
    region_to_rsids: dict[str, list[str]],
    regions: Iterable[str],
) -> dict[str, pd.DataFrame]:
    out: dict[str, pd.DataFrame] = {}
    for region in regions:
        sheet = "Full_Global_Freqs" if region == "Full_Region" else f"{region}_Freqs"
        df = read_excel(hap_stats_path, sheet)
        rsid_cols = [col for col in region_to_rsids[region] if col in df.columns]
        keep = ["Haplotype_ID", "Frequency", "Count", "Variant_Content"] + rsid_cols
        out[region] = df[keep].copy()
    return out


def parse_gt(gt: str) -> tuple[int, int] | None:
    if pd.isna(gt):
        return None
    text = str(gt).strip()
    if text in {"", ".", "./.", ".|.", "nan"}:
        return None
    delim = "|" if "|" in text else "/" if "/" in text else None
    if delim is None:
        return None
    left, right = text.split(delim)
    if left not in {"0", "1"} or right not in {"0", "1"}:
        return None
    return int(left), int(right)


def get_sample_sets(meta: pd.DataFrame, comparison: str) -> tuple[list[str], list[str]]:
    if comparison == "Breast":
        sub = meta[meta["Cohort"].eq("Breast")].copy()
    elif comparison == "Endometrium":
        sub = meta[meta["Cohort"].str.contains("Endomet", case=False, na=False)].copy()
    elif comparison == "All":
        sub = meta.copy()
    else:
        raise ValueError(f"Unsupported comparison: {comparison}")
    tumour = sub[sub["Tissue"].eq("Tumour")]["Sample"].astype(str).tolist()
    healthy = sub[sub["Tissue"].eq("Healthy")]["Sample"].astype(str).tolist()
    return tumour, healthy


def region_target_bits(
    freq_defs: dict[str, pd.DataFrame],
    region: str,
    haplotype_id: str,
    region_rsids: list[str],
) -> tuple[str, dict[str, str]]:
    row = freq_defs[region].loc[freq_defs[region]["Haplotype_ID"].eq(haplotype_id)]
    if row.empty:
        raise KeyError(f"Haplotype {haplotype_id} not found in {region}")
    row = row.iloc[0]
    bits = []
    allele_state: dict[str, str] = {}
    for rsid in region_rsids:
        value = row.get(rsid)
        is_alt = pd.notna(value) and int(float(value)) == 2
        bits.append("1" if is_alt else "0")
        allele_state[rsid] = "ALT" if is_alt else "REF"
    return "".join(bits), allele_state

def fetch_gt_value(phased_by_pos: pd.DataFrame, pos: int, sample: str):
    value = phased_by_pos.loc[pos, sample]
    if isinstance(value, pd.Series):
        return value.iloc[0]
    return value


def compute_haplotype_dosages(
    phased_by_pos: pd.DataFrame,
    region_positions: list[int],
    sample_names: Iterable[str],
    target_bits: str,
) -> pd.Series:
    dosage = {}
    for sample in sample_names:
        if sample not in phased_by_pos.columns:
            continue
        bits_a = []
        bits_b = []
        callable_sample = True
        for pos in region_positions:
            if pos not in phased_by_pos.index:
                callable_sample = False
                break
            parsed = parse_gt(fetch_gt_value(phased_by_pos, pos, sample))
            if parsed is None:
                callable_sample = False
                break
            a, b = parsed
            bits_a.append(str(a))
            bits_b.append(str(b))
        if not callable_sample:
            continue
        dosage[sample] = int("".join(bits_a) == target_bits) + int("".join(bits_b) == target_bits)
    return pd.Series(dosage, name="Dosage")


def compute_snp_alt_dosage(phased_by_pos: pd.DataFrame, pos: int, sample_names: Iterable[str]) -> pd.Series:
    dosage = {}
    if pos not in phased_by_pos.index:
        return pd.Series(dtype=float, name="Alt_Dosage")
    for sample in sample_names:
        if sample not in phased_by_pos.columns:
            continue
        parsed = parse_gt(fetch_gt_value(phased_by_pos, pos, sample))
        if parsed is None:
            continue
        dosage[sample] = sum(parsed)
    return pd.Series(dosage, name="Alt_Dosage")


def dosage_shift_label(case_pct_1: float, ctrl_pct_1: float, case_pct_2: float, ctrl_pct_2: float) -> str:
    het_delta = abs(case_pct_1 - ctrl_pct_1)
    hom_delta = abs(case_pct_2 - ctrl_pct_2)
    if hom_delta > het_delta + 5:
        return "Homozygous-dominant shift"
    if het_delta > hom_delta + 5:
        return "Heterozygous-dominant shift"
    return "Mixed/balanced shift"


def summarise_haplotype_dosage(
    hap_rows: pd.DataFrame,
    freq_defs: dict[str, pd.DataFrame],
    region_to_rsids: dict[str, list[str]],
    region_to_pos: dict[str, list[int]],
    phased_by_pos: pd.DataFrame,
    meta: pd.DataFrame,
) -> pd.DataFrame:
    rows = []
    for row in hap_rows.itertuples(index=False):
        tumour_samples, healthy_samples = get_sample_sets(meta, row.Comparison)
        target_bits, _ = region_target_bits(freq_defs, row.Region, row.Haplotype_ID, region_to_rsids[row.Region])
        tumour_dosage = compute_haplotype_dosages(phased_by_pos, region_to_pos[row.Region], tumour_samples, target_bits)
        healthy_dosage = compute_haplotype_dosages(phased_by_pos, region_to_pos[row.Region], healthy_samples, target_bits)
        if tumour_dosage.empty or healthy_dosage.empty:
            continue
        tumour_counts = tumour_dosage.value_counts().reindex([0, 1, 2], fill_value=0)
        healthy_counts = healthy_dosage.value_counts().reindex([0, 1, 2], fill_value=0)
        tumour_pct = (tumour_counts / tumour_counts.sum()) * 100.0
        healthy_pct = (healthy_counts / healthy_counts.sum()) * 100.0
        rows.append({
            "Region": row.Region,
            "Comparison": row.Comparison,
            "Haplotype_ID": row.Haplotype_ID,
            "Haplotype_Effect": row.Haplotype_Effect,
            "Target_Haplotype_Bits": target_bits,
            "N_Tumour_Callable": int(tumour_counts.sum()),
            "N_Healthy_Callable": int(healthy_counts.sum()),
            "Tumour_Dose0": int(tumour_counts[0]),
            "Tumour_Dose1": int(tumour_counts[1]),
            "Tumour_Dose2": int(tumour_counts[2]),
            "Healthy_Dose0": int(healthy_counts[0]),
            "Healthy_Dose1": int(healthy_counts[1]),
            "Healthy_Dose2": int(healthy_counts[2]),
            "Tumour_Dose0_%": float(tumour_pct[0]),
            "Tumour_Dose1_%": float(tumour_pct[1]),
            "Tumour_Dose2_%": float(tumour_pct[2]),
            "Healthy_Dose0_%": float(healthy_pct[0]),
            "Healthy_Dose1_%": float(healthy_pct[1]),
            "Healthy_Dose2_%": float(healthy_pct[2]),
            "Dominant_Dosage_Shift": dosage_shift_label(float(tumour_pct[1]), float(healthy_pct[1]), float(tumour_pct[2]), float(healthy_pct[2])),
        })
    return pd.DataFrame(rows)


def summarise_snp_genotypes(
    sig_snps: pd.DataFrame,
    rsid_to_pos: dict[str, int],
    phased_by_pos: pd.DataFrame,
    meta: pd.DataFrame,
) -> pd.DataFrame:
    rows = []
    for snp in sig_snps.itertuples(index=False):
        pos = rsid_to_pos.get(snp.SNP_ID)
        if pos is None:
            continue
        tumour_samples, healthy_samples = get_sample_sets(meta, snp.Comparison)
        tumour_dosage = compute_snp_alt_dosage(phased_by_pos, pos, tumour_samples)
        healthy_dosage = compute_snp_alt_dosage(phased_by_pos, pos, healthy_samples)
        if tumour_dosage.empty or healthy_dosage.empty:
            continue
        tumour_counts = tumour_dosage.value_counts().reindex([0, 1, 2], fill_value=0)
        healthy_counts = healthy_dosage.value_counts().reindex([0, 1, 2], fill_value=0)
        tumour_pct = (tumour_counts / tumour_counts.sum()) * 100.0
        healthy_pct = (healthy_counts / healthy_counts.sum()) * 100.0
        tumour_mean = float(tumour_dosage.mean())
        healthy_mean = float(healthy_dosage.mean())
        phased_effect = "Balanced"
        if tumour_mean > healthy_mean + 0.02:
            phased_effect = "Tumour-enriched"
        elif tumour_mean < healthy_mean - 0.02:
            phased_effect = "Healthy-enriched"
        rows.append({
            "Comparison": snp.Comparison,
            "SNP_ID": snp.SNP_ID,
            "Gene": snp.Symbol,
            "LD_Block_ID": snp.LD_Block_ID,
            "Stage12_OR": float(snp.Odds_Ratio),
            "Stage12_FDR": float(snp.FDR_P_Value),
            "Stage12_Effect": snp.SNP_Effect,
            "Phased_GT_Effect": phased_effect,
            "Tumour_WT": int(tumour_counts[0]),
            "Tumour_Het": int(tumour_counts[1]),
            "Tumour_Hom": int(tumour_counts[2]),
            "Healthy_WT": int(healthy_counts[0]),
            "Healthy_Het": int(healthy_counts[1]),
            "Healthy_Hom": int(healthy_counts[2]),
            "Tumour_WT_%": float(tumour_pct[0]),
            "Tumour_Het_%": float(tumour_pct[1]),
            "Tumour_Hom_%": float(tumour_pct[2]),
            "Healthy_WT_%": float(healthy_pct[0]),
            "Healthy_Het_%": float(healthy_pct[1]),
            "Healthy_Hom_%": float(healthy_pct[2]),
            "Mean_Alt_Dosage_Tumour": tumour_mean,
            "Mean_Alt_Dosage_Healthy": healthy_mean,
            "Dominant_Genotype_Shift": dosage_shift_label(float(tumour_pct[1]), float(healthy_pct[1]), float(tumour_pct[2]), float(healthy_pct[2])),
        })
    return pd.DataFrame(rows)


def expected_snp_effect_from_haplotype(haplotype_effect: str, allele_state: str) -> str:
    if haplotype_effect not in {"Tumour-enriched", "Healthy-enriched"}:
        return "Balanced"
    if allele_state == "ALT":
        return haplotype_effect
    return "Healthy-enriched" if haplotype_effect == "Tumour-enriched" else "Tumour-enriched"


def build_haplotype_snp_links(
    primary_haps: pd.DataFrame,
    sig_snps: pd.DataFrame,
    snp_genotypes: pd.DataFrame,
    freq_defs: dict[str, pd.DataFrame],
    region_to_rsids: dict[str, list[str]],
) -> pd.DataFrame:
    geno_lookup = snp_genotypes.set_index(["Comparison", "SNP_ID"], drop=False)
    rows = []
    for hap in primary_haps.itertuples(index=False):
        region_rsids = region_to_rsids[hap.Region]
        _, allele_states = region_target_bits(freq_defs, hap.Region, hap.Haplotype_ID, region_rsids)
        overlap = sig_snps[sig_snps["Comparison"].eq(hap.Comparison) & sig_snps["SNP_ID"].isin(region_rsids)].copy()
        if overlap.empty:
            rows.append({
                "Region": hap.Region,
                "Comparison": hap.Comparison,
                "Haplotype_ID": hap.Haplotype_ID,
                "Haplotype_Effect": hap.Haplotype_Effect,
                "Haplotype_FDR": hap.FDR,
                "Linked_SNP_ID": None,
                "Consistency_Call": "No overlapping significant SNP",
            })
            continue
        for snp in overlap.itertuples(index=False):
            geno_row = None
            if (hap.Comparison, snp.SNP_ID) in geno_lookup.index:
                maybe = geno_lookup.loc[(hap.Comparison, snp.SNP_ID)]
                geno_row = maybe.iloc[0] if isinstance(maybe, pd.DataFrame) else maybe
            expected = expected_snp_effect_from_haplotype(hap.Haplotype_Effect, allele_states[snp.SNP_ID])
            observed = geno_row["Phased_GT_Effect"] if geno_row is not None else None
            if observed in {None, "Balanced"}:
                consistency = "Ambiguous"
            elif observed == expected:
                consistency = "Consistent"
            else:
                consistency = "Discordant"
            rows.append({
                "Region": hap.Region,
                "Comparison": hap.Comparison,
                "Haplotype_ID": hap.Haplotype_ID,
                "Haplotype_Effect": hap.Haplotype_Effect,
                "Haplotype_FDR": hap.FDR,
                "Linked_SNP_ID": snp.SNP_ID,
                "Linked_SNP_Gene": snp.Symbol,
                "Linked_SNP_LD_Block": snp.LD_Block_ID,
                "Linked_SNP_Stage12_FDR": float(snp.FDR_P_Value),
                "Allele_State_In_Haplotype": allele_states[snp.SNP_ID],
                "Expected_SNP_Effect_From_Haplotype": expected,
                "Observed_SNP_Effect_From_PhasedGT": observed,
                "Observed_SNP_Effect_From_Stage12": snp.SNP_Effect,
                "Consistency_Call": consistency,
                "Tumour_WT": geno_row["Tumour_WT"] if geno_row is not None else np.nan,
                "Tumour_Het": geno_row["Tumour_Het"] if geno_row is not None else np.nan,
                "Tumour_Hom": geno_row["Tumour_Hom"] if geno_row is not None else np.nan,
                "Healthy_WT": geno_row["Healthy_WT"] if geno_row is not None else np.nan,
                "Healthy_Het": geno_row["Healthy_Het"] if geno_row is not None else np.nan,
                "Healthy_Hom": geno_row["Healthy_Hom"] if geno_row is not None else np.nan,
                "Dominant_Genotype_Shift": geno_row["Dominant_Genotype_Shift"] if geno_row is not None else None,
            })
    return pd.DataFrame(rows)


def best_primary_haplotype_rows(sig_haps: pd.DataFrame) -> pd.DataFrame:
    if sig_haps.empty:
        return sig_haps
    best = sig_haps.sort_values(["FDR", "P_Fisher", "Primary_Comparison_Rank"], kind="stable").groupby(["Region", "Haplotype_ID"], as_index=False).first()
    return best.sort_values(["FDR", "P_Fisher", "Region"], kind="stable").reset_index(drop=True)


def phased_haplotype_frequency(
    phased_by_pos: pd.DataFrame,
    region_positions: list[int],
    sample_names: Iterable[str],
    target_bits: str,
) -> tuple[float, int]:
    dosage = compute_haplotype_dosages(phased_by_pos, region_positions, sample_names, target_bits)
    if dosage.empty:
        return (math.nan, 0)
    n = int(dosage.shape[0])
    return (float(dosage.sum() / (2 * n)), n)

def build_frequency_checks(
    primary_haps: pd.DataFrame,
    freq_defs: dict[str, pd.DataFrame],
    region_to_rsids: dict[str, list[str]],
    region_to_pos: dict[str, list[int]],
    phased_by_pos: pd.DataFrame,
    meta: pd.DataFrame,
    hap_stats_female_path: Path,
    compare_path: Path,
    female_subset_info: dict[str, object],
) -> pd.DataFrame:
    fixed_compare = read_excel(compare_path, "Fixed_Region_Compare")
    conc = read_excel(compare_path, "Concordance_Summary")
    female_verified = bool(female_subset_info.get("verified"))
    female_freq_defs = load_freq_sheet_definitions(hap_stats_female_path, region_to_rsids, primary_haps["Region"].dropna().unique()) if female_verified else {}
    all_samples = meta["Sample"].astype(str).tolist()
    rows = []
    for hap in primary_haps.itertuples(index=False):
        target_bits, _ = region_target_bits(freq_defs, hap.Region, hap.Haplotype_ID, region_to_rsids[hap.Region])
        freq_row = freq_defs[hap.Region].loc[freq_defs[hap.Region]["Haplotype_ID"].eq(hap.Haplotype_ID)].iloc[0]
        if female_verified and hap.Region in female_freq_defs:
            female_row = female_freq_defs[hap.Region].loc[female_freq_defs[hap.Region]["Haplotype_ID"].eq(hap.Haplotype_ID)]
            female_freq = float(female_row.iloc[0]["Frequency"]) if not female_row.empty else math.nan
        else:
            female_freq = math.nan

        tumour_samples, healthy_samples = get_sample_sets(meta, hap.Comparison)
        overall_freq, n_all = phased_haplotype_frequency(phased_by_pos, region_to_pos[hap.Region], all_samples, target_bits)
        tumour_freq, n_tumour = phased_haplotype_frequency(phased_by_pos, region_to_pos[hap.Region], tumour_samples, target_bits)
        healthy_freq, n_healthy = phased_haplotype_frequency(phased_by_pos, region_to_pos[hap.Region], healthy_samples, target_bits)

        eur_row = fixed_compare[
            fixed_compare["Region"].eq(hap.Region)
            & fixed_compare["Population"].eq("EUR")
            & fixed_compare["Study_Haplotype_ID"].eq(hap.Haplotype_ID)
        ]
        eur_ref_freq = float(eur_row.iloc[0]["Reference_Frequency"]) if not eur_row.empty else math.nan
        eur_abs_delta = float(eur_row.iloc[0]["Abs_Frequency_Difference"]) if not eur_row.empty else math.nan

        conc_row = conc[conc["Region"].eq(hap.Region) & conc["Population"].eq("EUR")]
        shared_mass = float(conc_row.iloc[0]["Shared_Frequency_Mass"]) if not conc_row.empty and pd.notna(conc_row.iloc[0]["Shared_Frequency_Mass"]) else math.nan
        jsd = float(conc_row.iloc[0]["Jensen_Shannon_Distance"]) if not conc_row.empty and pd.notna(conc_row.iloc[0]["Jensen_Shannon_Distance"]) else math.nan
        exact_match = bool(conc_row.iloc[0]["Exact_Block_Match"]) if not conc_row.empty and pd.notna(conc_row.iloc[0]["Exact_Block_Match"]) else math.nan

        rows.append({
            "Region": hap.Region,
            "Comparison": hap.Comparison,
            "Haplotype_ID": hap.Haplotype_ID,
            "Assoc_Global_Freq": float(hap.Global_Freq),
            "FreqSheet_Global_Freq": float(freq_row["Frequency"]),
            "Phased_Global_Freq_Recomputed": overall_freq,
            "Abs_Delta_Assoc_vs_Recomputed": abs(float(hap.Global_Freq) - overall_freq),
            "Assoc_Tumour_Freq": float(hap.Freq_Tumour),
            "Phased_Tumour_Freq_Recomputed": tumour_freq,
            "Abs_Delta_Tumour": abs(float(hap.Freq_Tumour) - tumour_freq),
            "Assoc_Healthy_Freq": float(hap.Freq_Healthy),
            "Phased_Healthy_Freq_Recomputed": healthy_freq,
            "Abs_Delta_Healthy": abs(float(hap.Freq_Healthy) - healthy_freq),
            "Callable_All_Samples_Recomputed": n_all,
            "Callable_Tumour_Samples_Recomputed": n_tumour,
            "Callable_Healthy_Samples_Recomputed": n_healthy,
            "FemaleOnly_Study_Global_Freq": female_freq,
            "FemaleOnly_Study_Available": bool(female_subset_info.get("available")),
            "FemaleOnly_Study_Verified": female_verified,
            "FemaleOnly_Study_Filter_Mode": str(female_subset_info.get("sample_filter_mode", "")),
            "FemaleOnly_Study_Filter_File": str(female_subset_info.get("sample_filter_file", "")),
            "FemaleOnly_Study_Note": str(female_subset_info.get("note", "")),
            "Abs_Delta_Main_vs_FemaleOnly": abs(float(freq_row["Frequency"]) - female_freq) if pd.notna(female_freq) else math.nan,
            "EUR_Female_Reference_Freq": eur_ref_freq,
            "Abs_Delta_Study_vs_EUR_Female": eur_abs_delta,
            "EUR_Shared_Frequency_Mass": shared_mass,
            "EUR_Jensen_Shannon_Distance": jsd,
            "EUR_Exact_Block_Match": exact_match,
        })
    return pd.DataFrame(rows)


def build_dataset_consistency(sig_haps: pd.DataFrame, frequency_checks: pd.DataFrame) -> pd.DataFrame:
    if sig_haps.empty:
        return pd.DataFrame()
    pivot = sig_haps.pivot_table(index=["Region", "Haplotype_ID"], columns="Comparison", values=["OR", "FDR", "Freq_Tumour", "Freq_Healthy"], aggfunc="first")
    pivot.columns = ["_".join([str(part) for part in col if str(part) != ""]).strip("_") for col in pivot.columns]
    out = pivot.reset_index().merge(
        frequency_checks[[
            "Region", "Haplotype_ID", "FemaleOnly_Study_Global_Freq", "Abs_Delta_Main_vs_FemaleOnly",
            "EUR_Female_Reference_Freq", "Abs_Delta_Study_vs_EUR_Female", "EUR_Shared_Frequency_Mass",
            "EUR_Jensen_Shannon_Distance", "EUR_Exact_Block_Match",
        ]],
        on=["Region", "Haplotype_ID"],
        how="left",
    )

    def classify(row: pd.Series) -> str:
        breast_sig = pd.notna(row.get("FDR_Breast")) and row.get("FDR_Breast", 1.0) <= FDR_THRESHOLD
        endo_sig = pd.notna(row.get("FDR_Endometrium")) and row.get("FDR_Endometrium", 1.0) <= FDR_THRESHOLD
        all_sig = pd.notna(row.get("FDR_All")) and row.get("FDR_All", 1.0) <= FDR_THRESHOLD
        if breast_sig and endo_sig:
            return "Shared across tumour cohorts"
        if breast_sig:
            return "Breast-driven"
        if endo_sig:
            return "Endometrium-driven"
        if all_sig:
            return "Global only"
        return "Not significant after deduplication"

    out["Study_Cohort_Consistency"] = out.apply(classify, axis=1)
    return out.sort_values(["Region", "Haplotype_ID"], kind="stable")


def build_primary_haplotype_table(
    primary_haps: pd.DataFrame,
    hap_links: pd.DataFrame,
    frequency_checks: pd.DataFrame,
    region_to_rsids: dict[str, list[str]],
) -> pd.DataFrame:
    link_summary = hap_links.dropna(subset=["Linked_SNP_ID"]).groupby(["Region", "Comparison", "Haplotype_ID"], as_index=False).agg(
        Overlapping_Significant_SNPs=("Linked_SNP_ID", lambda s: "; ".join(s.astype(str))),
        Consistency_Summary=("Consistency_Call", lambda s: "; ".join(sorted(set(s.astype(str))))),
    )
    out = primary_haps.merge(link_summary, on=["Region", "Comparison", "Haplotype_ID"], how="left")
    out = out.merge(
        frequency_checks[[
            "Region", "Comparison", "Haplotype_ID", "Phased_Global_Freq_Recomputed",
            "Abs_Delta_Assoc_vs_Recomputed", "EUR_Female_Reference_Freq",
            "EUR_Shared_Frequency_Mass", "EUR_Jensen_Shannon_Distance",
        ]],
        on=["Region", "Comparison", "Haplotype_ID"],
        how="left",
    )
    out["Region_SNPs"] = out["Region"].map(lambda region: "; ".join(region_to_rsids.get(region, [])))
    return out.sort_values(["FDR", "P_Fisher"], kind="stable")


def plot_shared_genomic_map(
    primary_haps: pd.DataFrame,
    sig_snps: pd.DataFrame,
    hap_links: pd.DataFrame,
    region_to_span: dict[str, tuple[int, int]],
    region_to_pos: dict[str, list[int]],
    out_path: Path,
) -> None:
    if primary_haps.empty:
        return

    plot_haps = primary_haps.copy()
    plot_haps["Region_Start"] = plot_haps["Region"].map(lambda region: region_to_span[region][0])
    plot_haps = plot_haps.sort_values(["Region_Start", "FDR"], kind="stable").reset_index(drop=True)
    plot_haps["y"] = list(range(len(plot_haps), 0, -1))

    link_plot = hap_links.dropna(subset=["Linked_SNP_ID"]).copy()
    if not link_plot.empty:
        link_plot["SNP_POS"] = link_plot["Linked_SNP_ID"].astype(str).str.extract(r"\|(\d+)_", expand=False).astype(float)
        link_plot = link_plot.dropna(subset=["SNP_POS"]).copy()
        link_plot["SNP_POS"] = link_plot["SNP_POS"].astype(int)
    plot_haps = plot_haps.merge(
        link_plot.groupby(["Region", "Comparison", "Haplotype_ID"], as_index=False).agg(
            Linked_SNP_Label=("Linked_SNP_ID", lambda s: ", ".join(s.astype(str))),
        ),
        on=["Region", "Comparison", "Haplotype_ID"],
        how="left",
    )

    fig, ax = plt.subplots(figsize=(18, 10))
    for row in plot_haps.itertuples(index=False):
        start, end = region_to_span[row.Region]
        y = row.y
        color = HAP_EFFECT_COLORS.get(row.Haplotype_Effect, "#6c757d")
        linewidth = 14 if row.Region == "Full_Region" else 8
        ax.hlines(y, start / 1e6, end / 1e6, color=color, lw=linewidth, alpha=0.9, zorder=1)
        for pos in region_to_pos[row.Region]:
            ax.vlines(pos / 1e6, y - 0.16, y + 0.16, color="white", lw=1.2, alpha=0.95, zorder=2)

        linked = link_plot[
            link_plot["Region"].eq(row.Region)
            & link_plot["Comparison"].eq(row.Comparison)
            & link_plot["Haplotype_ID"].eq(row.Haplotype_ID)
        ].drop_duplicates(["Linked_SNP_ID", "SNP_POS"])
        if not linked.empty:
            ax.scatter(
                linked["SNP_POS"] / 1e6,
                np.repeat(y, len(linked)),
                s=52,
                color="white",
                edgecolor="black",
                linewidth=0.8,
                zorder=4,
            )
            label_y = y + (0.34 if row.Region != "Full_Region" else 0.45)
            for i, link in enumerate(linked.sort_values("SNP_POS").itertuples(index=False)):
                x = link.SNP_POS / 1e6
                ax.text(
                    x,
                    label_y + (0.16 if i % 2 else 0.0),
                    str(link.Linked_SNP_ID),
                    ha="center",
                    va="bottom",
                    fontsize=7.5,
                    rotation=35,
                    bbox=dict(boxstyle="round,pad=0.18", fc="white", ec="#d0d0d0", alpha=0.9),
                    zorder=5,
                )

        ax.text(
            end / 1e6 + 0.012,
            y,
            f"{row.Region} {row.Haplotype_ID} [{row.Comparison}]",
            va="center",
            ha="left",
            fontsize=9,
        )

    snp_plot = sig_snps.drop_duplicates(["Comparison", "SNP_ID"]).copy()
    snp_plot["y"] = 0.2
    for row in snp_plot.itertuples(index=False):
        pos = None
        match = re.search(r"\|(\d+)_", str(row.SNP_ID))
        if match is not None:
            pos = int(match.group(1))
        if pos is None:
            continue
        marker = COMPARISON_MARKERS.get(row.Comparison, "o")
        color = HAP_EFFECT_COLORS.get(row.SNP_Effect, "#6c757d")
        size = max(60, -math.log10(max(float(row.FDR_P_Value), 1e-12)) * 42)
        ax.scatter(pos / 1e6, row.y, marker=marker, s=size, color=color, edgecolor="black", linewidth=0.6, zorder=3)
        ax.text(pos / 1e6, row.y - 0.28, row.SNP_ID, rotation=45, ha="right", va="top", fontsize=8)

    ax.set_xlabel("Chr17 position (Mb)")
    ax.set_yticks([0.2] + plot_haps["y"].tolist())
    ax.set_yticklabels(["Significant SNPs"] + plot_haps["Haplotype_ID"].astype(str).tolist())
    ax.set_title("Haplotype-first genomic map with linked significant SNPs")
    ax.grid(axis="x", linestyle=":", alpha=0.35)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.set_axisbelow(True)

    hap_handles = [plt.Line2D([0], [0], color=color, lw=8, label=label) for label, color in HAP_EFFECT_COLORS.items()]
    snp_handles = [plt.Line2D([0], [0], marker=marker, linestyle="", markerfacecolor="#666666", markeredgecolor="black", label=label) for label, marker in COMPARISON_MARKERS.items()]
    linked_handle = plt.Line2D([0], [0], marker="o", linestyle="", markerfacecolor="white", markeredgecolor="black", label="Linked SNP on haplotype row")
    ax.legend(handles=hap_handles + snp_handles + [linked_handle], loc="upper left", frameon=False, ncol=2)
    fig.tight_layout()
    fig.savefig(out_path, dpi=250, bbox_inches="tight")
    plt.close(fig)

def plot_dosage_genotype_heatmap(
    hap_dosage: pd.DataFrame,
    snp_genotypes: pd.DataFrame,
    primary_haps: pd.DataFrame,
    out_path: Path,
) -> None:
    top_haps = primary_haps.head(8)[["Region", "Comparison", "Haplotype_ID"]].copy()
    hap_heat = hap_dosage.merge(top_haps, on=["Region", "Comparison", "Haplotype_ID"], how="inner")
    rows = []
    for _, row in hap_heat.iterrows():
        rows.append({
            "Label": f"HAP {row['Region']} {row['Haplotype_ID']} [{row['Comparison']}]",
            "WT_or_Dose0_Delta": row["Tumour_Dose0_%"] - row["Healthy_Dose0_%"],
            "Het_or_Dose1_Delta": row["Tumour_Dose1_%"] - row["Healthy_Dose1_%"],
            "Hom_or_Dose2_Delta": row["Tumour_Dose2_%"] - row["Healthy_Dose2_%"],
        })
    for _, row in snp_genotypes.sort_values(["Stage12_FDR", "Comparison", "SNP_ID"], kind="stable").head(12).iterrows():
        rows.append({
            "Label": f"SNP {row['SNP_ID']} [{row['Comparison']}]",
            "WT_or_Dose0_Delta": row["Tumour_WT_%"] - row["Healthy_WT_%"],
            "Het_or_Dose1_Delta": row["Tumour_Het_%"] - row["Healthy_Het_%"],
            "Hom_or_Dose2_Delta": row["Tumour_Hom_%"] - row["Healthy_Hom_%"],
        })
    heat_df = pd.DataFrame(rows)
    if heat_df.empty:
        return
    matrix = heat_df.set_index("Label")
    fig_height = max(6.0, 0.32 * len(matrix) + 2.2)
    fig, ax = plt.subplots(figsize=(11, fig_height))
    sns.heatmap(
        matrix,
        cmap="RdBu_r",
        center=0,
        linewidths=0.6,
        linecolor="white",
        cbar_kws={"label": "Tumour minus healthy percentage points"},
        ax=ax,
    )
    ax.set_title("Dosage/genotype separation for primary haplotypes and significant SNPs")
    ax.set_xlabel("")
    ax.set_ylabel("")
    fig.tight_layout()
    fig.savefig(out_path, dpi=250, bbox_inches="tight")
    plt.close(fig)


def dataframe_from_lines(lines: list[str]) -> pd.DataFrame:
    return pd.DataFrame({"Notes": lines})


def main() -> None:
    paths = harmonised_defaults()
    out_dir = ensure_dir(paths["out_dir"])
    out_xlsx = out_dir / "22_Haplotype_First_Interpretation.xlsx"
    out_map = out_dir / "22_Haplotype_First_Genomic_Map.png"
    out_heatmap = out_dir / "22_Haplotype_SNP_Dose_Genotype_Shifts.png"

    sig_haps = load_significant_haplotypes(paths["hap_stats"])
    sig_snps = load_significant_snps(paths["snp_enrichment"])
    snps_used, region_to_rsids, region_to_pos, region_to_span = load_region_lookup(paths["hap_stats"], paths["hap_compare"])
    freq_defs = load_freq_sheet_definitions(paths["hap_stats"], region_to_rsids, sig_haps["Region"].dropna().unique())

    phased = pd.read_csv(paths["phased"], sep="\t", dtype=str)
    phased["POS"] = phased["POS"].astype(int)
    phased_by_pos = phased.set_index("POS")
    meta = pd.read_csv(paths["sample_meta"], sep="\t", dtype=str)
    meta = meta[meta["Sample"].isin(phased.columns[5:])].copy()
    rsid_to_pos = dict(zip(snps_used["rsID"].astype(str), snps_used["POS"].astype(int)))

    primary_haps = best_primary_haplotype_rows(sig_haps)
    hap_dosage = summarise_haplotype_dosage(primary_haps, freq_defs, region_to_rsids, region_to_pos, phased_by_pos, meta)
    snp_genotypes = summarise_snp_genotypes(sig_snps, rsid_to_pos, phased_by_pos, meta)
    hap_links = build_haplotype_snp_links(primary_haps, sig_snps, snp_genotypes, freq_defs, region_to_rsids)
    female_subset_info = inspect_female_subset_workbook(paths["hap_stats_female"])
    frequency_checks = build_frequency_checks(primary_haps, freq_defs, region_to_rsids, region_to_pos, phased_by_pos, meta, paths["hap_stats_female"], paths["hap_compare"], female_subset_info)
    dataset_consistency = build_dataset_consistency(sig_haps, frequency_checks)
    primary_table = build_primary_haplotype_table(primary_haps, hap_links, frequency_checks, region_to_rsids)

    plot_shared_genomic_map(primary_haps, sig_snps, hap_links, region_to_span, region_to_pos, out_map)
    plot_dosage_genotype_heatmap(hap_dosage, snp_genotypes, primary_haps, out_heatmap)

    notes = [
        "Primary significance source: stage-15 haplotype tumour-vs-healthy results restricted to Full_Region and r2_080 LD blocks.",
        "Supporting SNP significance source: stage-12 LD-block-aware SNP enrichment results (Global/Breast/Endometrium sheets).",
        "Genotype labels use the same convention as stage 17: 0/0 = WT, 0/1 or 1/0 = Het, 1/1 = Hom.",
        "Haplotype dosage is the haplotype analogue of WT/Het/Hom: dosage 0 / 1 / 2.",
        "Genotype and dosage summaries were recomputed from phased study genotypes so haplotype and SNP summaries use the same backbone.",
        "1000 Genomes reference context comes from the female-filtered comparison output generated in stage 19.",
        str(female_subset_info.get("note", "")),
        "Full_Region links are intentionally broad; LD-block rows provide the explicit local haplotype-to-SNP mapping.",
    ]

    with pd.ExcelWriter(out_xlsx) as writer:
        dataframe_from_lines(notes).to_excel(writer, sheet_name="README", index=False)
        primary_table.to_excel(writer, sheet_name="Primary_Haplotypes", index=False)
        hap_links.to_excel(writer, sheet_name="Haplotype_SNP_Comparison", index=False)
        hap_dosage.to_excel(writer, sheet_name="Haplotype_Dosage_Summary", index=False)
        snp_genotypes.to_excel(writer, sheet_name="SNP_Genotype_Summary", index=False)
        frequency_checks.to_excel(writer, sheet_name="Frequency_Checks", index=False)
        dataset_consistency.to_excel(writer, sheet_name="Dataset_Consistency", index=False)
        snps_used.to_excel(writer, sheet_name="Backbone_SNPs", index=False)

    print(f"Wrote workbook: {out_xlsx}")
    print(f"Wrote map:      {out_map}")
    print(f"Wrote heatmap:  {out_heatmap}")


if __name__ == "__main__":
    main()
